name: Dockerize Machine Learning Project

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main ]

jobs:
  build-containers:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      # Build and push to docker.io repo
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          # Use docker.io for Docker Hub if empty
          REGISTRY: docker.io
          # github.repository as <account>/<repo>
          image: rkorivi/ml_project
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: latest, ${{ github.run_number }}
